# Generated by Django 5.0 on 2023-12-16 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pub_date",
        ),
    ]
